enum ActionTypes {
  SET_TASK_LISTS = "SET_TASK_LISTS",
  SET_SELECTED_TASK_LIST = "SET_SELECTED_TASK_LIST",
  TOGGLE_TASK_COMPLETED = "TOGGLE_TASK_COMPLETED",
  TOGGLE_TASK_IMPORTANT = "TOGGLE_TASK_IMPORTANT",
  ADD_TASK = "ADD_TASK",
  DELETE_TASK = "DELETE_TASK",
  ADD_TASKLIST = "ADD_TASKLIST",
  DELETE_TASKLIST = "DELETE_TASKLIST",
  RENAME_TASKLIST = "RENAME_TASKLIST",
  DUPLICATE_TASKLIST = "DUPLICATE_TASKLIST",
}

export default ActionTypes;
