enum ActionTypes {
  SET_TASK_LISTS = "SET_TASK_LISTS",
  SET_SELECTED_TASK_LIST = "SET_SELECTED_TASK_LIST",
  SET_TASK_COMPLETED = "SET_TASK_COMPLETED",
  SET_TASK_IMPORTANT = "SET_TASK_IMPORTANT",
}

export default ActionTypes;
