enum ActionTypes {
  SET_TASK_LISTS = "SET_TASK_LISTS",
  SET_SELECTED_TASK_LIST = "SET_SELECTED_TASK_LIST",
  TOGGLE_TASK_COMPLETED = "TOGGLE_TASK_COMPLETED",
  TOGGLE_TASK_IMPORTANT = "TOGGLE_TASK_IMPORTANT",
}

export default ActionTypes;
